"""C09 graph builder patch reference.

Do not copy blindly. Merge the ideas into existing backend/app/services/graph_builder.py.

Expected existing C08 chain:
    physical_column -> output_column -> query_result:final

C09 adds for metric expressions:
    physical_column -> expression -> output_column -> query_result:final
"""

from __future__ import annotations

from typing import Any


def build_c09_expression_nodes_and_edges(
    metrics: list[dict[str, Any]],
    existing_nodes: list[dict[str, Any]],
    existing_edges: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Return extra graph nodes/edges for expression metrics.

    Parameters
    ----------
    metrics:
        semantics_report["metrics"] generated by ExpressionAnalyzer.
    existing_nodes / existing_edges:
        current graph_view_model nodes and edges from C03-C08.

    Notes
    -----
    This helper uses dicts because the current project may already have Pydantic models.
    Adapt field names to your actual GraphNode / GraphEdge classes.
    """

    node_ids = {node.get("id") for node in existing_nodes}
    edge_ids = {edge.get("id") for edge in existing_edges}

    extra_nodes: list[dict[str, Any]] = []
    extra_edges: list[dict[str, Any]] = []

    for metric in metrics:
        name = metric["name"]
        expression_id = f"expression:{name}"
        output_id = f"output_column:{name}"

        if expression_id not in node_ids:
            extra_nodes.append(
                {
                    "id": expression_id,
                    "entity_id": expression_id,
                    "type": "expression",
                    "label": f"{name} expression",
                    "data": {
                        "node_type": "expression",
                        "name": name,
                        "expression": metric.get("expression"),
                        "depends_on": metric.get("depends_on", []),
                        "aggregate_functions": metric.get("aggregate_functions", []),
                        "operators": metric.get("operators", []),
                        "function_names": metric.get("function_names", []),
                        "description": metric.get("description"),
                        "confidence_level": metric.get("confidence_level", "high"),
                    },
                }
            )
            node_ids.add(expression_id)

        # source column -> expression
        for dep in metric.get("depends_on", []):
            source_id = _guess_column_node_id(dep)
            # If current graph uses another node id convention, adapt here by searching entity_id.
            if not _node_exists(source_id, existing_nodes, extra_nodes):
                # Conservative fallback: create a lightweight unknown/source column node.
                extra_nodes.append(
                    {
                        "id": source_id,
                        "entity_id": f"column:{dep}",
                        "type": "column",
                        "label": dep,
                        "data": {"node_type": "column", "name": dep, "source": "c09_expression_dependency"},
                    }
                )
                node_ids.add(source_id)

            edge_id = f"edge:{source_id}->{expression_id}:expression_dependency"
            if edge_id not in edge_ids:
                extra_edges.append(
                    {
                        "id": edge_id,
                        "source": source_id,
                        "target": expression_id,
                        "type": "expression_dependency",
                        "label": "depends",
                        "data": {
                            "edge_type": "expression_dependency",
                            "provenance": "sqlglot_ast",
                            "metric_name": name,
                        },
                    }
                )
                edge_ids.add(edge_id)

        # expression -> output_column
        edge_id = f"edge:{expression_id}->{output_id}:expression_to_output"
        if edge_id not in edge_ids and _node_exists(output_id, existing_nodes, extra_nodes):
            extra_edges.append(
                {
                    "id": edge_id,
                    "source": expression_id,
                    "target": output_id,
                    "type": "expression_to_output",
                    "label": "produces",
                    "data": {
                        "edge_type": "expression_to_output",
                        "provenance": "sqlglot_ast",
                        "metric_name": name,
                    },
                }
            )
            edge_ids.add(edge_id)

    return extra_nodes, extra_edges


def _guess_column_node_id(dep: str) -> str:
    # Existing C03-C08 commonly uses column:<table>.<column>.
    return dep if dep.startswith("column:") else f"column:{dep}"


def _node_exists(node_id: str, *node_groups: list[dict[str, Any]]) -> bool:
    for group in node_groups:
        for node in group:
            if node.get("id") == node_id or node.get("entity_id") == node_id:
                return True
    return False


def assert_no_dangling_edges(nodes: list[dict[str, Any]], edges: list[dict[str, Any]]) -> None:
    node_ids = {node["id"] for node in nodes}
    dangling = [edge for edge in edges if edge.get("source") not in node_ids or edge.get("target") not in node_ids]
    if dangling:
        raise AssertionError(f"Graph has dangling edges: {dangling}")
