insert overwrite table ihotel_default.dw_ihotel_abtest_index_searchlist_di
    partition (dt = '${zdt.addDay(-1).format("yyyy-MM-dd")}', type = 'searchlist', user_id_type)
select
    ab_exp_id,
    ab_version,
    ab_rule_version,
    ab_exp_value,
    datee,
    search_request_uid,
    hotel_seq,
    user_id,
    detail_log_id,
    detail_device_id,
    device_id,
    orig_device_id,
    rank,
    sort_price,
    order_info_device_id,
    is_display,
    render_price,
    qpayprice,
    cpayprice,
    is_query,
    is_same_city,
    is_filter,
    intention,
    suggest_type,
    country_name,
    province_name,
    checkin_date,
    checkout_date,
    log_datetime,
    total_hotels,
    intention1,
    country,
    product_range,
    new_render_price,
    new_sort_price,
    order_info_order_no,
    click_rank,
    order_rank,
    medal_type,
    show_commission,
    sort_v2_price,
    rn,
    newolduser,
    highlowstar,
    null as order_datee,
    null as order_orig_device_id,
    null as order_user_id,
    null as order_order_no,
    null as order_hotel_seq,
    null as order_room_night,
    null as order_checkin_date,
    null as order_checkout_date,
    null as order_init_gmv,
    null as order_order_commission,
    user_id_type
from ihotel_default.dw_ihotel_abtest_detail_searchlist_di
where dt = '${zdt.addDay(-1).format("yyyy-MM-dd")}'
;