from __future__ import annotations


SQL_PARSE_ERROR = "SQL_PARSE_ERROR"
UNKNOWN_COLUMN = "UNKNOWN_COLUMN"
AMBIGUOUS_COLUMN = "AMBIGUOUS_COLUMN"
UNKNOWN_TABLE_ALIAS = "UNKNOWN_TABLE_ALIAS"
UNSUPPORTED_SELECT_STAR = "UNSUPPORTED_SELECT_STAR"
UNSUPPORTED_COMPLEX_QUERY = "UNSUPPORTED_COMPLEX_QUERY"
SELECT_STAR_METADATA_REQUIRED = "SELECT_STAR_METADATA_REQUIRED"
METADATA_MISSING = "METADATA_MISSING"
